apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cache-hit-run-multi-
spec:
  pipelineRef:
    name: cache-hit-pipeline
  params:
    - name: namespace
      value: "llm-d"
    - name: gateway-url
      value: "http://llm-d-infra-inference-gateway-istio.llm-d.svc.cluster.local"
    - name: host
      value: "llm-d-infra-inference-gateway.localhost"
    - name: requests
      value: "25"
    - name: sleep-seconds
      value: "0.3"
    - name: warmup-count
      value: "1"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cache-hit-run-multi-
spec:
  pipelineRef:
    name: cache-hit-pipeline
  params:
    - name: namespace
      value: "llm-d"
    - name: gateway-url
      value: "http://llm-d-infra-inference-gateway-istio.llm-d.svc.cluster.local"
    - name: host
      value: "llm-d-infra-inference-gateway.localhost"
    - name: requests
      value: "25"
    - name: sleep-seconds
      value: "0.3"
    - name: warmup-count
      value: "1"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cache-hit-run-multi-
spec:
  pipelineRef:
    name: cache-hit-pipeline
  params:
    - name: namespace
      value: "llm-d"
    - name: gateway-url
      value: "http://llm-d-infra-inference-gateway-istio.llm-d.svc.cluster.local"
    - name: host
      value: "llm-d-infra-inference-gateway.localhost"
    - name: requests
      value: "25"
    - name: sleep-seconds
      value: "0.3"
    - name: warmup-count
      value: "1"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cache-hit-run-multi-
spec:
  pipelineRef:
    name: cache-hit-pipeline
  params:
    - name: namespace
      value: "llm-d"
    - name: gateway-url
      value: "http://llm-d-infra-inference-gateway-istio.llm-d.svc.cluster.local"
    - name: host
      value: "llm-d-infra-inference-gateway.localhost"
    - name: requests
      value: "25"
    - name: sleep-seconds
      value: "0.3"
    - name: warmup-count
      value: "1"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cache-hit-run-multi-
spec:
  pipelineRef:
    name: cache-hit-pipeline
  params:
    - name: namespace
      value: "llm-d"
    - name: gateway-url
      value: "http://llm-d-infra-inference-gateway-istio.llm-d.svc.cluster.local"
    - name: host
      value: "llm-d-infra-inference-gateway.localhost"
    - name: requests
      value: "25"
    - name: sleep-seconds
      value: "0.3"
    - name: warmup-count
      value: "1"

