apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-3-2-1b-epp-pd-config
  namespace: llm-d
data:
  pd-config.yaml: |
    # P/D Disaggregation Configuration for LLM-D
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: prefill-header-handler
    - type: prefill-filter
    - type: decode-filter  
    - type: max-score-picker
    - type: queue-scorer
      parameters:
        hashBlockSize: 16
        maxPrefixBlocksToMatch: 256
        lruCapacityPerServer: 1000
    - type: pd-profile-handler
      parameters:
        threshold: 10  # Enable P/D for prompts > 10 tokens
        hashBlockSize: 16
    schedulingProfiles:
    - name: prefill
      plugins:
      - pluginRef: prefill-filter
      - pluginRef: queue-scorer
        weight: 1.0
      - pluginRef: max-score-picker
    - name: decode
      plugins:
      - pluginRef: decode-filter
      - pluginRef: queue-scorer
        weight: 1.0
      - pluginRef: max-score-picker
