apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: llm-d-frontend
    component: frontend
    part-of: llm-d-demo
  name: llm-d-frontend
  namespace: llm-d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-d-frontend
  template:
    metadata:
      labels:
        app: llm-d-frontend
        component: frontend
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        image: quay.io/cnuland/llm-interface:frontend-simple-v2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: frontend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
