global:
  security:
    allowInsecureImages: true
  istio:
    enabled: false  # Explicitly disable Istio

modelservice:
  enabled: true
  resources:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    nvidia.com/gpu: "true"

sampleApplication:
  enabled: true
  model:
    modelArtifactURI: hf://meta-llama/Llama-3.2-3B-Instruct
    modelName: "meta-llama/Llama-3.2-3B-Instruct"
  resources:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    nvidia.com/gpu: "true"

gateway:
  enabled: true  # Enable Envoy Gateway

ingress:
  enabled: false  # Disable default ingress since we're using OpenShift Routes
