# Values to render Llama-3.2-3B-Instruct model workloads without an operator
multinode: false

modelArtifacts:
  uri: "hf://meta-llama/Llama-3.2-3B-Instruct"
  size: 50Gi
  authSecretName: "llm-d-hf-token"

routing:
  modelName: meta-llama/Llama-3.2-3B-Instruct
  servicePort: 8000
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: llm-d-gateway

  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0
    connector: nixlv2
    secure: false

  inferenceModel:
    create: false

  inferencePool:
    create: false
    name: llm-d

  httpRoute:
    create: true

  epp:
    create: true

decode:
  create: true
  replicas: 1
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d:v0.2.0"
    modelCommand: vllmServe
    args:
      - "--enable-prefix-caching"
      - "--prefix-caching-hash-algo=builtin"
      - "--block-size=16"
      - "--gpu-memory-utilization=0.7"
      - "--max-model-len=4096"
      - "--kv-cache-dtype=auto"
      - "--max-num-seqs=256"
      - "--enforce-eager"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    env:
      - name: PYTHONHASHSEED
        value: "42"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: llm-d-hf-token
            key: HF_TOKEN
    ports:
      - containerPort: 5557
        protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    mountModelVolume: true
    volumeMounts:
      - name: metrics-volume
        mountPath: /.config
      - name: torch-compile-cache
        mountPath: /.cache
  volumes:
    - name: metrics-volume
      emptyDir: {}
    - name: torch-compile-cache
      emptyDir: {}

prefill:
  create: true
  replicas: 1
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d:v0.2.0"
    modelCommand: vllmServe
    args:
      - "--enforce-eager"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
      - "--max-model-len"
      - "4096"
    env:
      - name: PYTHONHASHSEED
        value: "42"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: llm-d-hf-token
            key: HF_TOKEN
    ports:
      - containerPort: 8000
        protocol: TCP
      - containerPort: 5557
        protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    mountModelVolume: true
    volumeMounts:
      - name: metrics-volume
        mountPath: /.config
      - name: torch-compile-cache
        mountPath: /.cache
  volumes:
    - name: metrics-volume
      emptyDir: {}
    - name: torch-compile-cache
      emptyDir: {}

