apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: llama-3-2-1b-session-affinity
  namespace: llm-d
  labels:
    app: cache-aware
spec:
  host: llama-3-2-1b-cache-aware-service.llm-d.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "x-session-id"
        minimumRingSize: 4096
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
        maxRequestsPerConnection: 10
        maxRetries: 3
        idleTimeout: 900s
        h2UpgradePolicy: UPGRADE
