apiVersion: llm-d.ai/v1alpha1
kind: ModelService
metadata:
  name: llama-3-2-1b-enhanced
  namespace: llm-d
  labels:
    app: enhanced-cache-aware-routing
spec:
  baseConfigMapRef:
    name: basic-gpu-with-enhanced-cache-routing
  decode:
    acceleratorTypes:
      labelKey: nvidia.com/gpu.present
      labelValues:
      - "true"
    containers:
    - env:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            key: HF_TOKEN
            name: llm-d-hf-token
      name: vllm
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
    replicas: 3
  modelArtifacts:
    authSecretName: llm-d-hf-token
    size: 50Gi
    uri: hf://meta-llama/Llama-3.2-1B
  prefill:
    containers:
    - env:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            key: HF_TOKEN
            name: llm-d-hf-token
      name: vllm
    replicas: 2
  routing:
    gatewayRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: llm-d-gateway
      namespace: llm-d
    modelName: llama-3-2-1b-enhanced
