apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"creationTimestamp":"2025-07-30T21:19:09Z","generation":1,"labels":{"app":"llm-d"},"name":"vllm-metrics","namespace":"llm-d","resourceVersion":"4468934","uid":"a1a8931f-7bc5-4a13-85a1-b7be1c272fd2"},"spec":{"endpoints":[{"interval":"15s","path":"/metrics","port":"metrics"}],"selector":{"matchLabels":{"llm-d.ai/role":"decode"}}}}
  creationTimestamp: "2025-07-30T21:19:09Z"
  generation: 1
  labels:
    app: llm-d
  name: vllm-metrics
  namespace: llm-d
  resourceVersion: "9271680"
  uid: a1a8931f-7bc5-4a13-85a1-b7be1c272fd2
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      llm-d.ai/role: decode
