apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app":"llm-d"},"name":"llm-d-all-metrics","namespace":"llm-d"},"spec":{"endpoints":[{"interval":"15s","path":"/metrics","port":"vllm","targetPort":8000},{"interval":"15s","path":"/metrics","port":"nixl","targetPort":5557}],"selector":{"matchLabels":{"llmd.ai/gather-metrics":"true"}}}}
    creationTimestamp: "2025-07-31T00:53:39Z"
    generation: 1
    labels:
      app: llm-d
    name: llm-d-all-metrics
    namespace: llm-d
    resourceVersion: "4698512"
    uid: 49dea41a-129f-4ef9-ac54-bd3e0ad688b8
  spec:
    endpoints:
    - interval: 15s
      path: /metrics
      port: vllm
      targetPort: 8000
    - interval: 15s
      path: /metrics
      port: nixl
      targetPort: 5557
    selector:
      matchLabels:
        llmd.ai/gather-metrics: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app":"llm-d"},"name":"llm-d-epp-service-metrics","namespace":"llm-d"},"spec":{"endpoints":[{"interval":"15s","path":"/metrics","port":"metrics","scheme":"http"}],"selector":{"matchLabels":{"app.kubernetes.io/gateway":"llm-d-operator-inference-gateway","llmd.ai/gather-metrics":"true"}}}}
    creationTimestamp: "2025-07-31T00:53:39Z"
    generation: 1
    labels:
      app: llm-d
    name: llm-d-epp-service-metrics
    namespace: llm-d
    resourceVersion: "4698515"
    uid: a4cfd1c9-d0d7-41b7-b021-50da9d326313
  spec:
    endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
      scheme: http
    selector:
      matchLabels:
        app.kubernetes.io/gateway: llm-d-operator-inference-gateway
        llmd.ai/gather-metrics: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app":"llm-d"},"name":"llm-d-modelservice-metrics","namespace":"llm-d"},"spec":{"endpoints":[{"interval":"15s","path":"/metrics","port":"vllm","scheme":"http"},{"interval":"15s","path":"/metrics","port":"vllm","scheme":"http"}],"selector":{"matchLabels":{"llmd.ai/gather-metrics":"true"}}}}
    creationTimestamp: "2025-07-31T00:53:39Z"
    generation: 1
    labels:
      app: llm-d
    name: llm-d-modelservice-metrics
    namespace: llm-d
    resourceVersion: "4698516"
    uid: 02b0553b-3930-46b6-9d2f-665c8373e5d3
  spec:
    endpoints:
    - interval: 15s
      path: /metrics
      port: vllm
      scheme: http
    - interval: 15s
      path: /metrics
      port: vllm
      scheme: http
    selector:
      matchLabels:
        llmd.ai/gather-metrics: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: llm-d-operator
      meta.helm.sh/release-namespace: llm-d
    creationTimestamp: "2025-07-29T21:19:43Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: llm-d-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: llm-d
      app.kubernetes.io/version: "0.1"
      helm.sh/chart: llm-d-1.0.23
    name: llm-d-operator-llm-d-operator-modelservice-epp-monitor
    namespace: llm-d
    resourceVersion: "3037551"
    uid: c17b8b20-8f6b-471d-ae49-ac16a72bb3f6
  spec:
    endpoints:
    - authorization:
        credentials:
          key: token
          name: llm-d-operator-llm-d-operator-modelservice-epp-metrics-scrape-token
      interval: 10s
      path: /metrics
      port: metrics
    jobLabel: llm-d-operator-llm-d-operator-modelservice-epp
    namespaceSelector:
      matchNames:
      - llm-d
    selector:
      matchLabels:
        llmd.ai/gather-metrics: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: llm-d-operator
      meta.helm.sh/release-namespace: llm-d
    creationTimestamp: "2025-07-29T21:19:43Z"
    generation: 1
    labels:
      app.kubernetes.io/component: modelservice
      app.kubernetes.io/instance: llm-d-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: llm-d
      app.kubernetes.io/version: "0.1"
      helm.sh/chart: llm-d-1.0.23
    name: llm-d-operator-modelservice-monitor
    namespace: llm-d
    resourceVersion: "3037553"
    uid: 9248b926-c4f1-43eb-8173-eb34dbd7082c
  spec:
    endpoints:
    - interval: 15s
      path: /metrics
      port: vllm
    jobLabel: llm-d-operator-modelservice
    namespaceSelector:
      matchNames:
      - llm-d
    selector:
      matchLabels:
        llmd.ai/gather-metrics: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2025-07-30T21:19:09Z"
    generation: 1
    labels:
      app: llm-d
    name: vllm-metrics
    namespace: llm-d
    resourceVersion: "4468934"
    uid: a1a8931f-7bc5-4a13-85a1-b7be1c272fd2
  spec:
    endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
    selector:
      matchLabels:
        llm-d.ai/role: decode
kind: List
metadata:
  resourceVersion: ""
