apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: llm-d-operator
  namespace: openshift-operators
spec:
  channel: "stable"
  name: llm-d-operator
  source: community-operators
  sourceNamespace: openshift-marketplace

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: llm-d-operator-group
  namespace: openshift-operators
spec:
  upgradeStrategy: Default
