apiVersion: v1
kind: Service
metadata:
  labels:
    app: llm-d-backend
  name: llm-d-backend-service
  namespace: llm-d
spec:
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: llm-d-backend
  type: ClusterIP
