apiVersion: batch/v1
kind: Job
metadata:
  name: guidellm-pd-benchmark
  namespace: llm-d
  labels:
    app: guidellm
    test-type: pd-disaggregation
spec:
  template:
    spec:
      containers:
      - name: guidellm
        image: quay.io/rh-aiservices-bu/guidellm:latest
        env:
        # IMPORTANT: Route through EPP service for P/D disaggregation testing
        - name: TARGET
          value: "http://llama-3-2-1b-epp-service.llm-d.svc.cluster.local:9002"
        - name: MODEL_NAME
          value: "meta-llama/Llama-3.2-1B"
        - name: OUTPUT_FILENAME
          value: "pd-benchmark-results"
        - name: RATE_TYPE
          value: "synchronous"
        - name: MAX_SECONDS
          value: "300"
        - name: PYTHONPATH
          value: "/opt/app-root/guidellm/lib64/python3.12/site-packages"
        command:
        - guidellm
        - benchmark
        - --target
        - $(TARGET)
        - --model
        - $(MODEL_NAME)
        # Test data designed to trigger P/D disaggregation with shared prefixes
        - --data
        - |
          [
            {"messages": [{"role": "user", "content": "What is artificial intelligence? Explain the key concepts and applications in detail."}]},
            {"messages": [{"role": "user", "content": "What is artificial intelligence? Explain the main types and their differences."}]},
            {"messages": [{"role": "user", "content": "What is artificial intelligence? Describe its impact on modern technology."}]},
            {"messages": [{"role": "user", "content": "What is machine learning? Explain how it relates to artificial intelligence."}]},
            {"messages": [{"role": "user", "content": "What is machine learning? Describe the different types of learning algorithms."}]},
            {"messages": [{"role": "user", "content": "What is deep learning? Explain neural networks and their applications."}]},
            {"messages": [{"role": "user", "content": "What is deep learning? Compare it with traditional machine learning methods."}]},
            {"messages": [{"role": "user", "content": "Explain natural language processing and its current state of the art."}]},
            {"messages": [{"role": "user", "content": "Describe computer vision applications in autonomous vehicles."}]},
            {"messages": [{"role": "user", "content": "What are the ethical considerations in AI development and deployment?"}]}
          ]
        - --rate-type
        - $(RATE_TYPE)
        - --output-path
        - /opt/app-root/src/output/
        - --max-seconds
        - $(MAX_SECONDS)
        - --max-requests
        - "30"
        - --request-rate
        - "2"
        volumeMounts:
        - name: guidellm-output
          mountPath: /opt/app-root/src/output
        - name: cache-volume
          mountPath: /opt/app-root/src/.cache
        workingDir: /opt/app-root/src
      volumes:
      - name: guidellm-output
        emptyDir: {}
      - name: cache-volume
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 3
