apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: llm-d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: llm-d
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    [auth]
    disable_login_form = false
    [security]
    admin_user = admin
    admin_password = admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: llm-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: llm-d
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: llm-d
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: grafana
