apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: llm-d-monitoring
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    [auth]
    disable_login_form = false
    [security]
    admin_user = admin
    admin_password = admin
    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

