apiVersion: v1
imagePullSecrets:
  - name: pipeline-dockercfg-zgppq
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: pipeline-dockercfg-zgppq
  name: pipeline
  namespace: llm-d
secrets:
  - name: pipeline-dockercfg-zgppq
