apiVersion: llm-d.ai/v1alpha1
kind: ModelService
metadata:
  name: llama-3-2-3b
  namespace: llm-d
spec:
  # Reference to the improved ConfigMap with P/D disaggregation enabled
  baseConfigMapRef:
    name: basic-gpu-with-nixl-and-pd-preset
  
  # Model configuration
  modelArtifacts:
    uri: "hf://meta-llama/Llama-3.2-3B"
    size: 50Gi
    authSecretName: "llm-d-hf-token"
  
  # Decode phase configuration
  decode:
    replicas: 1
    acceleratorTypes:
      labelKey: nvidia.com/gpu.present
      labelValues:
      - "true"
    containers:
    - name: vllm
      env:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            key: HF_TOKEN
            name: llm-d-hf-token
      resources:
        limits:
          nvidia.com/gpu: "2"  # 3B model needs 2 GPUs for better performance
        requests:
          nvidia.com/gpu: "2"
  
  # Prefill phase configuration
  prefill:
    replicas: 1
    containers:
    - name: vllm
      env:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            key: HF_TOKEN
            name: llm-d-hf-token
  
  # Routing configuration
  routing:
    modelName: llama-3-2-3b
    gatewayRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: llm-d-gateway
      namespace: llm-d
