apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: llm-d
  name: llm-d-epp-metrics
  namespace: llm-d
spec:
  podMetricsEndpoints:
    # EPP metrics (port 9090)
    - interval: 15s
      path: /metrics
      port: "9090"
  selector:
    matchLabels:
      app.kubernetes.io/gateway: llm-d-operator-inference-gateway
