apiVersion: v1
kind: Service
metadata:
  labels:
    app: llm-d
    component: metrics
  name: llm-d-metrics-aggregator
  namespace: llm-d
spec:
  ports:
    # Prefill metrics (port 8000)
    - name: prefill-metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
    # Decode metrics (port 8001)
    - name: decode-metrics
      port: 8001
      protocol: TCP
      targetPort: 8001
    # EPP metrics (port 9090)
    - name: epp-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    # This service will not select any pods directly
    # Instead, PodMonitors will scrape pods directly
    app: llm-d-metrics-placeholder
  type: ClusterIP
