apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: decode
    llm-d.ai/model: llama-3-2-1b
    llm-d.ai/role: decode
  name: llama-3-2-1b-decode-metrics
  namespace: llm-d
spec:
  clusterIP: 172.30.24.190
  clusterIPs:
    - 172.30.24.190
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: llama-3-2-1b
    llm-d.ai/role: decode
  sessionAffinity: None
  type: ClusterIP
