apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: llm-d
  name: vllm-pod-metrics
  namespace: llm-d
spec:
  podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      port: http
  selector:
    matchLabels:
      llm-d.ai/role: decode
