apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: llm-d
  name: llm-d-all-metrics
  namespace: llm-d
spec:
  endpoints:
    # vLLM metrics from prefill and decode services
    - interval: 15s
      path: /metrics
      port: vllm
      targetPort: 8000
    # NIXL metrics from prefill and decode services  
    - interval: 15s
      path: /metrics
      port: nixl
      targetPort: 5557
  selector:
    matchLabels:
      llmd.ai/gather-metrics: "true"
