apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: llm-d
  name: vllm-metrics
  namespace: llm-d
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      llm-d.ai/role: decode
