apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: envoy-gateway-scc
allowHostPorts: true
allowPrivilegedContainer: false
allowPrivilegeEscalation: true
allowHostNetwork: false
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostPID: false
readOnlyRootFilesystem: false
allowedCapabilities:
- NET_BIND_SERVICE
defaultAddCapabilities: null
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- emptyDir
- projected
- secret
- downwardAPI
priority: 0
