apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: llm-d-gateway-logs
  namespace: llm-d
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: llm-d-gateway
  accessLogging:
  - providers:
    - name: envoy
    disabled: false
    filter:
      # Only log traffic for our demo host
      expression: request.headers[":authority"] == "llm-d.demo.local"
    output:
      format: json
      json:
        start_time: "%START_TIME%"
        method: "%REQ(:METHOD)%"
        path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
        protocol: "%PROTOCOL%"
        response_code: "%RESPONSE_CODE%"
        duration: "%DURATION%"
        upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
        upstream_host: "%UPSTREAM_HOST%"
        route_name: "%ROUTE_NAME%"
        authority: "%REQ(:AUTHORITY)%"
        x_session_id: "%REQ(X-SESSION-ID)%"
        x_test_id: "%REQ(X-TEST-ID)%"
        user_agent: "%REQ(USER-AGENT)%"
        request_id: "%REQ(X-REQUEST-ID)%"
        downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"

