apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- utils/pvc.yaml
- utils/serviceaccount.yaml
- configs/config.yaml
- configs/env-config.yaml
- pipeline/tekton-task.yaml
- pipeline/tekton-pipeline.yaml

# Namespace for all resources
namespace: llm-d

# Common labels
commonLabels:
  app.kubernetes.io/name: guidellm
  app.kubernetes.io/component: benchmarking
  app.kubernetes.io/part-of: llm-d

# Resources are pre-cleaned of cluster-specific metadata
