apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations: {}
  name: llm-d-gateway
  namespace: llm-d
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
