apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations: {}
  name: llama-3-2-1b-http-route
  namespace: llm-d
spec:
  hostnames:
    - llm-d-inference-gateway-llm-d.apps.rhoai-cluster.qhxt.p1.openshiftapps.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: llm-d-gateway
      namespace: llm-d
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: llama-3-2-1b-epp-service
          port: 9002
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /v1
# NOTE: This HTTPRoute properly routes /v1/* requests to the EPP service
# which handles cache-aware routing to decode/prefill pods
