apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gatewayparameters.gateway.kgateway.dev
spec:
  group: gateway.kgateway.dev
  names:
    kind: GatewayParameters
    listKind: GatewayParametersList
    plural: gatewayparameters
    singular: gatewayparameters
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                kube:
                  type: object
                  properties:
                    envoyContainer:
                      type: object
                      properties:
                        securityContext:
                          type: object
                          properties:
                            allowPrivilegeEscalation:
                              type: boolean
                            readOnlyRootFilesystem:
                              type: boolean
                            runAsNonRoot:
                              type: boolean
                            runAsUser:
                              type: integer
                            seccompProfile:
                              type: object
                              properties:
                                type:
                                  type: string
                        bootstrap:
                          type: object
                          properties:
                            componentLogLevels:
                              type: object
                              properties:
                                upstream:
                                  type: string
                                http:
                                  type: string
                                connection:
                                  type: string
                            logLevel:
                              type: string
                    service:
                      type: object
                      properties:
                        type:
                          type: string
                        extraLabels:
                          type: object
                          additionalProperties:
                            type: string
                    podTemplate:
                      type: object
                      properties:
                        extraLabels:
                          type: object
                          additionalProperties:
                            type: string
                    sdsContainer:
                      type: object
                      properties:
                        securityContext:
                          type: object
                          properties:
                            allowPrivilegeEscalation:
                              type: boolean
                            readOnlyRootFilesystem:
                              type: boolean
                            runAsUser:
                              type: integer
                            seccompProfile:
                              type: object
                              properties:
                                type:
                                  type: string
